#!/bin/sh

#
#  STEP 1:
#  extract all Stud.IP message strings and merge them with the existing translations
#

LOCALE_RELATIVE_PATH="."
TRANSLATIONFILES_RELAVITVE_PATHS="../views ../controllers ../VideoPreview.class.php"

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po.old"
	> "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.pot"
	find $TRANSLATIONFILES_RELAVITVE_PATHS \( -iname "*.php" -o -iname "*.ihtml" \) | xargs xgettext --from-code=utf-8 -j -n --language=PHP -o "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.pot"
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po.old" && msgmerge "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po.old" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.pot" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/videopreview.po"
done
